### ISSUE TITLE
Add build error when using Derived fields in Mapping

### ISSUE THREAD

**Issue by Data-Nexus** [graphprotocol/graph-cli#959] opened 2022-09-13 19:21 UTC
It would be helpful to add a error when running `graph build` when you are attempting to utilize a derived field in your mappings. This gives unexpected nulls which takes a bit of time to troubleshoot.

Example:
schema.graphql
```
markets: [Market!]! @derivedFrom(field: "protocol")
```

mappings
```
export function UpdateProtocolLTV(blockNum: BigInt): void {
  let _lendingProtocol = GetProtocol();
  let _marketArray = _lendingProtocol.markets;
```

**Comment by azf20** [comment] 2022-09-15 13:38
Thanks @Data-Nexus, makes sense - I think this is a duplicate of https://github.com/graphprotocol/graph-cli/issues/943

**Closed by azf20** 2022-09-15 13:38 UTC
