### ISSUE TITLE
Install fails using commands available in ```The Grpah Studio``` section

### ISSUE THREAD

**Issue by DorianDaSilva** [graphprotocol/graph-cli#992] opened 2022-11-14 17:35 UTC
Hello,

@fordN 
I follow the steps to set up the graph studio as per the doc but install fails when yarn is installing dependencies.

Was unable to install dependencies using the cmd lines provided in ```the graph studio```. 
I tried the discord channel & creating an issue in the graph-cli repo but received no replies.

Issue remains as described in this discussion:
[| https://github.com/smartcontractkit/full-blockchain-solidity-course-js/discussions/3711#discussion-4549211 |
](https://github.com/graphprotocol/indexer/issues/540#issuecomment-1312143789)

I don't understand how I get this error running the commands provided by your team for that specific purpose. Any help would be appreciated, thank you!

**Comment by schmidsi** [comment] 2022-11-15 15:03
@DorianDaSilva is this a duplicate of #995 ?

**Comment by schmidsi** [comment] 2022-11-16 13:55
@DorianDaSilva we were able to roll out a fix. Can you please try to update your dependencies to using version 0.36.1 of graph-cli? That should fix your issue. If not, feel free to reopen this issue.

**Closed by schmidsi** 2022-11-16 13:55 UTC

**Comment by DorianDaSilva** [comment] 2022-11-16 16:15
@schmidsi It is not a duplicate of issue: https://github.com/graphprotocol/graph-cli/issues/995

I open a new issue as per your request: https://github.com/graphprotocol/graph-cli/issues/997

Thank you!
